# Generated by Django 4.2.7 on 2023-11-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Chofer', models.CharField(max_length=100)),
                ('Numero_de_Asientos', models.PositiveIntegerField()),
                ('Matricula', models.CharField(max_length=20)),
                ('Año', models.PositiveIntegerField()),
                ('Marca', models.CharField(max_length=50)),
                ('Tipo_de_bus', models.CharField(choices=[('Dos Pisos', 'Dos Pisos'), ('Un Piso', 'Un Piso')], max_length=10)),
                ('Empresa', models.CharField(max_length=100)),
            ],
        ),
    ]
